services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ianbrito/quote-api
    container_name: quote_api-api
    ports:
      - 8080:80
    networks:
      quote_net:
        ipv4_address: 172.16.10.3

  db:
    image: bitnami/mariadb:11.4
    container_name: quote_api-db
    expose:
      - 3306
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    networks:
      quote_net:
        ipv4_address: 172.16.10.2

volumes:
  mariadb_data:
    driver: local

networks:
  quote_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.10.0/28