// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createCarrier = `-- name: CreateCarrier :execresult
INSERT INTO
    carriers (reference, name, registered_number, state_inscription, logo_url)
VALUES (?, ?, ?, ?, ?)
`

type CreateCarrierParams struct {
	Reference        int64
	Name             string
	RegisteredNumber string
	StateInscription string
	LogoUrl          string
}

func (q *Queries) CreateCarrier(ctx context.Context, arg CreateCarrierParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCarrier,
		arg.Reference,
		arg.Name,
		arg.RegisteredNumber,
		arg.StateInscription,
		arg.LogoUrl,
	)
}

const createDispatcher = `-- name: CreateDispatcher :execresult
INSERT INTO
    dispatchers (id, request_id, registered_number_shipper, registered_number_dispatcher, zipcode_origin)
VALUES (?, ?, ?, ?, ?)
`

type CreateDispatcherParams struct {
	ID                         string
	RequestID                  string
	RegisteredNumberShipper    string
	RegisteredNumberDispatcher string
	ZipcodeOrigin              int32
}

func (q *Queries) CreateDispatcher(ctx context.Context, arg CreateDispatcherParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDispatcher,
		arg.ID,
		arg.RequestID,
		arg.RegisteredNumberShipper,
		arg.RegisteredNumberDispatcher,
		arg.ZipcodeOrigin,
	)
}

const createOffer = `-- name: CreateOffer :execresult
INSERT INTO
    offers (id, dispatcher_id, offer, simulation_type, carrier_id, service, service_code, service_description, delivery_time, original_delivery_time, identifier, delivery_note, home_delivery, carrier_needs_to_return_to_sender, expiration, cost_price, final_price, weights, composition, esg, modal)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOfferParams struct {
	ID                           string
	DispatcherID                 sql.NullString
	Offer                        int32
	SimulationType               int32
	CarrierID                    int64
	Service                      string
	ServiceCode                  sql.NullString
	ServiceDescription           sql.NullString
	DeliveryTime                 json.RawMessage
	OriginalDeliveryTime         json.RawMessage
	Identifier                   sql.NullString
	DeliveryNote                 sql.NullString
	HomeDelivery                 sql.NullBool
	CarrierNeedsToReturnToSender sql.NullBool
	Expiration                   time.Time
	CostPrice                    float64
	FinalPrice                   float64
	Weights                      json.RawMessage
	Composition                  json.RawMessage
	Esg                          json.RawMessage
	Modal                        sql.NullString
}

func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOffer,
		arg.ID,
		arg.DispatcherID,
		arg.Offer,
		arg.SimulationType,
		arg.CarrierID,
		arg.Service,
		arg.ServiceCode,
		arg.ServiceDescription,
		arg.DeliveryTime,
		arg.OriginalDeliveryTime,
		arg.Identifier,
		arg.DeliveryNote,
		arg.HomeDelivery,
		arg.CarrierNeedsToReturnToSender,
		arg.Expiration,
		arg.CostPrice,
		arg.FinalPrice,
		arg.Weights,
		arg.Composition,
		arg.Esg,
		arg.Modal,
	)
}
